name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Set default toolchain
        run: rustup default stable

      - name: Run tests
        run: cargo test --features extension

      - name: Verify release build
        run: cargo build --release --features extension

  fmt:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal --component rustfmt

      - name: Set default toolchain
        run: rustup default stable

      - name: Rustfmt
        run: cargo fmt --check
